---
- name: Install php-fpm and deps
  apt: pkg={{ item }} state=latest
  with_items:
    - imagemagick
    - php-gettext
    - php-pear
    - php-xml-parser
    - php5
    - php-apc
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-pgsql
    - php5-sqlite

- name: Configure PHP
  file: src={{ item }} dest=/etc/php5/fpm/{{ item }}
  notify: restart php-fpm
  with_items:
    - php.ini
    - php-fpm.conf

- name: Configure PHP-FPM pool
  template: src={{ item }}.j2 dest=/etc/php5/fpm/pool.d/{{ item }}
  notify: restart php-fpm
  with_items:
    - www.conf

- file: dest=/var/log/php5-fpm/ owner={{ nginx_user }} group={{ nginx_group }} state=directory

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm

# - name: Copy php-fpm configuration
#   template: src=wordpress.conf dest=/etc/php-fpm.d/
#   notify: restart php-fpm
