---
- name: Upgrade apt packages
  apt: upgrade=dist update_cache=yes

- name: Install git
  apt: pkg=git-core state=present

- name: Install NTP
  apt: pkg=ntp state=present

- include: etckeeper.yml
- include: hostname.yml
- include: backup-manager.yml
- include: utility.yml
